export const ACTIVITY_ACTION = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  CODE_SUBMIT: 'CODE_SUBMIT',
  BATCH_COMPLETED: 'BATCH_COMPLETED',
  CHALLENGE_GENERATE: 'CHALLENGE_GENERATE',
  CHALLENGE_REGENERATE: 'CHALLENGE_REGENERATE',
  CHALLENGE_EXPORT: 'CHALLENGE_EXPORT',
  CHALLENGE_LOCK: 'CHALLENGE_LOCK',
  CHALLENGE_UNLOCK: 'CHALLENGE_UNLOCK',
  CHALLENGE_DAILY_CRON: 'CHALLENGE_DAILY_CRON',
  BATCH_REPROCESS: 'BATCH_REPROCESS',
  SHOP_CREATE: 'SHOP_CREATE',
  SHOP_UPDATE: 'SHOP_UPDATE',
} as const;

export type ActivityAction =
  (typeof ACTIVITY_ACTION)[keyof typeof ACTIVITY_ACTION];
