export const ACTIVITY_ACTION = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  CODE_SUBMIT: 'CODE_SUBMIT',
  BATCH_COMPLETED: 'BATCH_COMPLETED',
  CHALLENGE_GENERATE: 'CHALLENGE_GENERATE',
  CHALLENGE_REGENERATE: 'CHALLENGE_REGENERATE',
  CHALLENGE_EXPORT: 'CHALLENGE_EXPORT',
  CHALLENGE_DAILY_CRON: 'CHALLENGE_DAILY_CRON',
} as const;

export type ActivityAction =
  (typeof ACTIVITY_ACTION)[keyof typeof ACTIVITY_ACTION];
